# ===================================================================
# ===================================================================

# ===================================================================
# ===================================================================

spring:
    application:
        name: MarketGateway
        basename: i18n/messages

# ===================================================================
# ===================================================================