server:
    port: 8585
 
spring:
    jackson:
        serialization.indent_output: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:3306}/${DATABASE_NAME:MarketGateway}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
        username: root
        password: ENC(R3ws1K71XbM3T3IbqKEbcQ==)
        initialization-mode: always
        schema: classpath:/schema.sql
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        generate-ddl: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect