spring:
    profiles:
        active: dev
    jackson:
        serialization.indent_output: true
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/MarketGateway
        username: root
        password: ENC(R3ws1K71XbM3T3IbqKEbcQ==)
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
# ===================================================================
# ===================================================================
server:
    port: 8585

# ===================================================================
# ===================================================================